### ISSUE TITLE
Thunderstorm Research

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#12]
# Information Needed:

**Comment by ConorMulcahy118** [comment]
Thunderstorm Research

Cause: Warm, moist air rises and forms clouds. As the air cools, water vapor begins to condense, releasing latent heat energy that allows the rising packet of warm air to cool less than surrounding air and thus rise higher to form cumulonimbus clouds. Within the cumulonimbus, lighter, positively charged particles form at the top while heavier, negative particles sink to the bottom. When these charges grow large enough, a spark occurs between them - lightning. Together with typical storm factors like low pressure zones, high wind speeds, and precipitation, a thunderstorm is thus formed. 

Effects:
Dangerous lightning strikes that can severely harm people if struck directly or while in contact with conductive material
Lightning can also heavily damage electrical systems and spark fires, causing extreme structural damage to buildings
Strong winds can damage property and turn loose objects into dangerous projectiles
Torrential precipitation can cause localized flooding
Strong enough hail can cause extensive property damage and physical harm

Emergency response:
Stay indoors
If you hear thunder, immediately find shelter in a substantial building or hard-topped metal vehicle
Avoid open areas and stay away from the tallest objects near you like trees - they can function as lightning rods
Avoid electrical appliances
Close and stay away from windows and doors, as glass can become a serious hazard in high winds

“The NWS stopped recommending the "lightning crouch" in 2008 as it doesn't provide a significant level of protection and will not significantly lower the risk of being killed or injured from a nearby lightning strike.”

Is it linked to climate change:

Yes, though more by severity than an increase in occurrence. Warmer temperatures will entail higher humidity levels in the air as well as warmer ocean waters; thus, storms that would have formed already will have more moisture to draw on, resulting in heavier precipitation. 

“Severe thunderstorms are defined as having sustained winds above 93 kilometers (58 miles) per hour or unusually large hail, and there are two key factors that fuel their formation: convective available potential energy (CAPE) and strong wind shear. CAPE is a measure of how much raw energy is available for storms; it relates to how warm, moist, and buoyant air is in a given area. Wind shear is a measure of how the speed and direction of winds change with altitude.

“CAPE can provide storms with the raw fuel to produce rain and hail, and vertical wind shear can pull and twist weak storms into strong, windy ones,” explained Harold Brooks, a meteorologist at NOAA’s National Severe Storms Laboratory.

Scientists have evidence that global warming should increase CAPE by warming the surface and putting more moisture in the air through evaporation. On the other hand, disproportionate warming in the Arctic should lead to less wind shear in mid-latitude areas prone to severe thunderstorms. So one factor makes severe storms more likely, while the other makes them less so.”

Where does this happen: Thunderstorms occur all over the world, even in polar regions.

Different levels (magnitudes): Many countries use the term Severe Thunderstorm to classify extremely dangerous storms as they appear. The criteria for a storm to become severe are linked to tornado warnings, projected minimum hail size, minimum wind speed, and minimum rainfall per hour.

https://en.wikipedia.org/wiki/Thundersnow
