### ISSUE TITLE
Proposal - High Level Development Plan

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#28]
The milestone section outlines the weekly goals (items to be completed in order to realize the feature list in section 2.1.4) that need to be met in order to keep the project development on track. Refer to the milestone dates to create a high-level development plan that your team can adhere to. Specify the dates along with the goals and high-level features that are to be completed for each week. Keep in mind design and development should be happening at the same time. • plan to use stand-in/temporary art while programming • create design/artwork to help guide the development and to use as tests • artists should be assisting with programming vs. “waiting for programming to be complete • Allow time for user testing

**Comment by antoinella** [comment]
2.1.5 - High Level Development Plan

	To accomplish our feature list that was described earlier, we have set ourselves weekly goals to accomplish. Our high-level development plan and weekly goals for our game is evident in the gantt chart depicted below. We have allocated sufficient time for designing 3D models, mockups, music, as well as programming and user testing. In addition, we blocked out some extra time at the end as a buffer in case potential issues and delays arrive later.
