### ISSUE TITLE
Proposal - Experience Flow / Architecture

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#30]
Using the supplied template, create an architecture that outlines the flow of the experience based on the user’s actions. In a standard web site project, the architecture would outline all of the pages belonging to the web site and how they connect/relate. In a project that is more freeform, such as a game experience, map the progression of the phases of the experience (flowchart) based on the probable use cases / persona stories.

**Comment by antoinella** [comment]
Experience Flow / Architecture
The experience flow and phase progression for the mobile/desktop player and VR player are illustrated below in Figures 1 and 2 respectively. 


Figure 1. Experience flow for mobile/desktop player






Figure 2. Experience flow for VR player

![Experience Flow - VR Player](https://user-images.githubusercontent.com/59921079/74073613-004d0580-49d9-11ea-80c4-a0ea8ef24a9e.png)
![Experience Flow - MobileDesktop Player](https://user-images.githubusercontent.com/59921079/74073615-00e59c00-49d9-11ea-8b52-457b26c39fff.png)

https://www.lucidchart.com/invitations/accept/1a44d467-2eb4-4772-adbb-411ae15da0dc
