### ISSUE TITLE
Proposal - Diagrams & Physical Layout

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#32]
Create diagrams/illustrations that illustrate your project’s physical setup. This should include the placement of equipment and the user’s position. This could simply be examples of what someone in VR/AR might look like from the outside interacting with a virtual world. The diagrams may be sketched by hand (professionally rendered, if so), created in a tool such as Adobe Illustrator, or in a 3D package (i.e. Maya). Many studios use Google Sketchup ( http://sketchup.google.com/ ) to create these diagrams as it is fast to use and has a great library of items (including objects and people) that can be used in the scene. The diagrams should be detailed enough so that a client who is uneducated regarding the project would gain a good understanding of the project’s construction, setup, and the user’s position.

**Comment by antoinella** [comment]
2.3 - Diagrams and Physical Layout
Figures 12-14 below display how players will be positioned in relation to the game’s physical setup using mobile/desktop and VR headset.

	Figure 12. Position of VR player in game setup
	
	Figure 13. Position of mobile player in game setup (if we choose mobile over desktop)
	
	Figure 14. Position of desktop player in game setup (if we choose desktop over mobile)

![Diagrams and Physical Layout_Physical Setup - Mobile Player](https://user-images.githubusercontent.com/59921079/74090833-24aeed80-4a7e-11ea-9d0a-a5210e4a6e55.png)
![Diagrams and Physical Layout_Physical Setup - VR Player](https://user-images.githubusercontent.com/59921079/74090834-25478400-4a7e-11ea-9620-ac148491b01b.png)
![Diagrams and Physical Layout_Physical Setup - Desktop Player](https://user-images.githubusercontent.com/59921079/74090835-25478400-4a7e-11ea-88dc-866b7ee37f00.png)
