### ISSUE TITLE
Proposal - Design Comps

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#33]
Two screens outlining the overall design direction and layout are to be created based on 2 screens from the wireframe document. The design comps should be polished and appear as though they are screengrabs from the completed project. Please include them as full-size images at the end of the PDF. (it is okay if the pages for the comps are larger in dimensions than the other pages, and landscape oriented, if necessary).

**Comment by antoinella** [comment]
Arina let me know if you need help!

**Comment by antoinella** [comment]
2.4 - Design Comps
Figures 20 and 21 below show two polished screens based on the wireframes in section 2.2. Figure 20 is a detailed version of the wireframe in Figure 10, whereas figure 21 is a detailed version of the wireframe in Figure 7. These two design compositions are also included as full-sized images at the end of this project proposal.


Figure 20. Target object for mobile/desktop player appears on screen for 5 seconds before switching to the drawing canvas interface.


Figure 21. “Student” has found the correct room and must now locate the correct object on the table using the “Professor’s” drawing as a reference
