### ISSUE TITLE
Professor Map

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#41]
Create a map that tracks the xz coordinates of the player in the vr environment and convert it to the xy positions to be displayed on a HTML canvas object

- [x] HTML Canvas object made
- [x] Player location tracked
- [x] Player location displayed
- [x] Maze image load and display
- [x] Hot cold implementation
- [ ] UI upgrades

**Comment by antoinella** [comment]
This is done and merged into master branch.
