### ISSUE TITLE
Canopic Jars 1-3

### ISSUE THREAD

**Issue by ConorMulcahy118** [EricLacey/BadWeather#44]
Models are in Maya file on drive (Assets folder), UV mapped

**Comment by antoinella** [comment]
Should we move this issue to the texture project board instead of 3d modelling?

**Comment by antoinella** [comment]
for canopic jar 1 (anubis), the base colour for the head and bottom are done. Working on the face and hair now. Haven't started canopic jar 2 and 3 yet.

**Comment by antoinella** [comment]
Canopic Jar 1 fully textured now, going to research how to bake in lighting in substance painter.

**Comment by antoinella** [comment]
need help with baked lighting if anyone has time

**Comment by antoinella** [comment]
Maxime said he would show me how to bake light into textures on thursday. In the mean time, I am texturing without baked lights.

**Comment by antoinella** [comment]
Done re-UVmapping canopic jar "horus" so that symbol only appears on chest once and not all over body.

**Comment by antoinella** [comment]
Put eyes and chest symbol texture on 3d model of horus jar.

**Comment by antoinella** [comment]
added gold to the head and dirt colour to the body. trying to add speckled rocks/dust to body texture

**Comment by antoinella** [comment]
Added spots/dust rock texture to horus jar body using smart masks "spots". 
![image](https://user-images.githubusercontent.com/59921079/75900656-3bd9c480-5e0b-11ea-924a-bedcf4085c0c.png)

**Comment by antoinella** [comment]
going to replace eye position once i figure out how I want the cheek design to look like: 
![image](https://user-images.githubusercontent.com/59921079/75905771-77788c80-5e13-11ea-9e49-12bf3858c308.png)

**Comment by antoinella** [comment]
Done horus canopic jar. Just have to bake the lighting in for the horus and anubis jars. Haven't started isis jar yet.
![image](https://user-images.githubusercontent.com/59921079/75911132-15248980-5e1d-11ea-81b3-91f8c02e382d.png)

**Comment by antoinella** [comment]
Starting on isis canopic jar. Fixed the uvmaps a little bit and added new version of maya master objects file: 
https://drive.google.com/open?id=1mriyZ0i2dKtzSL8Ipd1t_xHivQEK0PyD

**Comment by antoinella** [comment]
progress of texture on isis jar: 
![image](https://user-images.githubusercontent.com/59921079/76112318-f7d3f480-5faf-11ea-9541-a7b6aa116b15.png)

**Comment by antoinella** [comment]
need to add lips and fix neck area. figured out how to use symmetry in substance painter: 
![image](https://user-images.githubusercontent.com/59921079/76116095-59e42800-5fb7-11ea-85da-393e6584e19e.png)

**Comment by antoinella** [comment]
Conor suggested to tone down highlights of gold and to fix eyes on anubis model. Make them look more like a dog than a kangaroo.

**Comment by antoinella** [comment]
Fixed eyes for anubis model. Also exported all three canopic jars from substance painter.
https://drive.google.com/open?id=1M05Ap7Zk2MGcBQpfwGk7hsEfrCq86kH8

**Comment by antoinella** [comment]
Conor mentioned that the gold wasn't showing up when testing in A-frame. I can switch it to a yellow colour, worst case. I think also the a-frame environment needs light in order for the gold to reflect?
