### ISSUE TITLE
Proposal Document

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#5]
TP1 - The Proposal (8%)
Refer to Term Project Document for more information. If any questions please feel free to email Professor.

**Comment by antoinella** [comment]
https://docs.google.com/document/d/1xBSzjCePt5T3oBiRQDV0gCx4YuALXX--6lGTBl-5ZIY/edit?usp=sharing

**Comment by antoinella** [comment]
Ready to submit tonight, once reviewed/"okayed" by everyone.
