### ISSUE TITLE
Generate Social Media Strategy

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#7]
Generate a social media strategy for the team i.e. platforms, topics, etc.

**Comment by antoinella** [comment]
Sun Dog Studios - Social Media Strategy

Social Media Platform Choices
Facebook
Instagram
Twitter

Type of Posts
Inspirational success/tech/future/teamwork quotes:
“I failed my way to success.” - Thomas Edison
“Technology is best when it brings people together.” - Matt Mullenweg
“Teamwork makes the dream work”
Meet the team short bios - picture, fave quote, main roles, interests, fun fact (examples)
Eric
Fave quote: “Never underestimate the power of human stupidity”
Interests: VR, Science, Prop making
Fun fact: I’m Newfie-Sicilian, both islander, both loud, and both with accents/dialects the rest of their country’s can’t understand. Fortunately don’t have an accent though.
Or
I’m a spicy food fiend. If there’s a special “super hot” item on a menu, I always end up ordering it. I carry a hotsauce in my bag that you need to be 21 to buy, and I grow my own carolina reaper peppers to make hot sauces out of.
Conor
Fave quote:
Interests:
Fun fact:
Arina
Fave quote:
Interests:
Fun fact:
Nella
Fave quote: Everything happens for a reason
Interests: Photography, Video, Music
Fun fact: I once made my friends get off the bus to chase a sunset… I will think of something cooler lol
Behind the scenes
Brainstorming
Prototyping
3d modelling
Texturing
music/audio making
Progress
Sneak peak of game play demos
Educational fun facts / did you knows?
https://ioi.london/latest/five-surprising-facts-about-virtual-reality/
https://www.izmofx.com/article/9-interesting-facts-about-virtual-reality-2115-en-us.htm
https://www.maxboxvr.com/magazine/virtual-reality-facts-you-probably-didn-t-know
Weekly hashtags that could be used:
#MotivationalMonday
#TabooTuesday
#TipTuesday
#TechTuesday
#WisdomWednesday
#ThrowbackThursday
#ThursdayThoughts
#FlashbackFriday
#FunFactFriday
#SaturdayShoutOut
#StartupSunday
#SundayRead

Primary Target Audience
Early teens to young adults?
Ages 15-25?

Vocabulary
Relatable
Easy to understand
As if talking to a friend
Casual

Posting Strategy
Post 1-2 times per week on all platforms
Posts perform better during peak days/times of social media user activity:
Facebook Peak Times
Weekdays between 12pm-3pm
Weekends between 12pm-1pm
Wednesday is most popular day
Instagram Peak Times
Weekdays between 12pm-1pm & 7pm-9pm
Monday, Wednesday, and Thursday are most popular days
Twitter Peak Times
Weekdays between 9am-3pm
Monday, Tuesday, Wednesday, and Thursday are most popular days
Potential related hashtags to use:
#VR
#VirtualReality
#game
#experience
#headset
#future
#instaVR
#instaVirtualReality
#instaHeadset
#instaTechnology
#instaTech
#instaFuture
Potential tags and @mention handles:
Carleton University
Algonquin College
Any other ideas?
