### ISSUE TITLE
Create Asset List

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#8]
Develop a list of required assets for the project to be built over time

**Comment by antoinella** [comment]
Asset List

Environment
Museum area
4 wings to start?
Item drop zone
Display cases
Shelves
Set dressing
Objects
3 per wing
Reference image for each item
Short blurb for each item (historical context)
Icons for VR
Movement zones (teleporting?)
Mobile
Any icons

Music
Calm slow-paced background music when VR player is trying to find object
Faster-paced background music when VR player is running out of time to find object

Sound Effects
Text message sent sound effect when mobile player sends a drawing hint of object
Bad buzzer sound effect when VR player guesses wrong object?
Good check mark sound effect when VR player guesses winning object
Door opening/closing sound effects when entering/leaving different rooms?

Museum Brainstorm - Wings and Fetch Items

Ancient Greece/Rome
Amphora

Ancient Egypt
Canopic jar (3 variations)
Pharaoh bust (3 variations)
(keys?)
Makeup frog (3 variations)(https://www.britishmuseum.org/sites/default/files/styles/bm_gallery_medium_700h/public/2019-09/stone-vessel-frog-egypt-british-museum.jpg?itok=x2Q5I6s7)

Middle East
Winged lion statue (https://www.britishmuseum.org/sites/default/files/styles/bm_gallery_medium_700h/public/2019-09/Colossal%20statue%20of%20a%20winged%20lion%20from%20the%20North-West%20Palace%20of%20Ashurnasirpal%20II%20%28Room%20B%29%2C%20British%20Museum.jpg?itok=fD93_mtw)

Britain
Lewis chessmen

China
Jade sculpture

Japan
Samurai helmet
Dogu (https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Dogu_Miyagi_1000_BCE_400_BCE.jpg/220px-Dogu_Miyagi_1000_BCE_400_BCE.jpg)

Europe
Knight gear (armor/weapons)
Viking stuff

Africa
Shield (https://www.britishmuseum.org/sites/default/files/styles/bm_gallery_medium_700h/public/2019-10/west-papua-asmat-sheild-british-musuem.jpg?itok=TFvI7CGE)
Mask (e.g. https://www.britishmuseum.org/sites/default/files/styles/bm_gallery_medium_700h/public/2019-10/Mask%20%28kifwebe%29.jpg?itok=Q69jVkWo)
Sculpture

Polynesia
Moai

Americas
Mexican mosaics (https://www.britishmuseum.org/sites/default/files/styles/bm_gallery_medium_700h/public/2019-10/Mosaic%20of%20a%20double-headed%20serpent%2C%20Mexico%2C%20British%20Museum.jpg?itok=hW3tlalP)
Inuit sculpture (e.g. inukshuk)
Totem pole segment

India
Statuette (e.g. https://www.britishmuseum.org/sites/default/files/styles/bm_gallery_medium_700h/public/2019-10/shiva-nataraja-chola-british-museum.jpg?itok=S7rvLMZZ)

Other
Geode
Dinosaur bones/skull
Neolithic stuff
Wheel
Spear

https://docs.google.com/document/d/1gc8gcVKOZCBJ9LdGfqT4qW7K1O5WRrhePTseXwQcWoI/edit?usp=sharing
