### ISSUE TITLE
Pop-up fact about target artifact when game ends

### ISSUE THREAD

**Issue by antoinella** [EricLacey/BadWeather#87]
Research/facts about artifacts: https://docs.google.com/document/d/19zq-A6y6RV8wwJ0cWXuN9y2vhwzHI0Kecht-ziRxVog/edit?usp=sharing

**Comment by rereshek** [comment]
- [ ] Pop up screen
- [ ] artifact img
- [ ] description
- [ ] thank you for playing

**Comment by rereshek** [comment]
Have to link to the end action via sockets

**Comment by rereshek** [comment]
Plus just realized we forgot to create Dogu object lol
