### ISSUE TITLE
Edit Final Video 1 - Presentation (10-15mins)

### ISSUE THREAD

**Issue by antoinella** [EricLacey/BadWeather#92]

**Comment by antoinella** [comment]
sent to teammates for review: https://drive.google.com/open?id=1s7kF83lPDTNrKsa9PgH4CbDNrkMEKJ8B

**Comment by antoinella** [comment]
need to re-record walkthrough it looks too laggy. Conor will help.

**Comment by antoinella** [comment]
conor sent new demo footage, will start editing the video further: https://drive.google.com/open?id=12RAvxyOy1fP6Gm_FqT1hRHGBfMqWidOk

**Comment by antoinella** [comment]
Sent V2 for review.

**Comment by ghost** [comment]
Almost done, just need last audio recording. :)
